[[redirects]]
  from = "/api/coingecko/*"
  to = "https://api.coingecko.com/api/v3/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = true

[[headers]]
  for = "/.well-known/stellar.toml"
  [headers.values]
    Content-Type = "text/plain"
    Access-Control-Allow-Origin = "*"
